version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: rituraj_db
      POSTGRES_USER: rituraj_db_user
      POSTGRES_PASSWORD: rituraj_db_pass
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: