name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        echo "Installing project dependencies..."
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        echo "Running tests..."
        pytest tests/

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build Docker images
      run: |
        echo "Building Docker images..."
        docker-compose build
        echo "Docker images built successfully!"

#   deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Deploy to hosting platform
      env:
        HOST_PASSWORD: ${{ secrets.HOST_PASSWORD }}
      run: |
        echo "Deploying to remote host..."
        scp -r ./app user@remote-host:/path/to/deploy
        echo "Application code copied to remote host."
        ssh user@remote-host "
          echo 'Stopping existing containers on remote host...'
          cd /path/to/deploy
          docker-compose down
          echo 'Starting new containers on remote host...'
          docker-compose up -d
          echo 'Deployment completed successfully!'
        "