name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services: # PostgreSQL service
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres  # Default username
          POSTGRES_PASSWORD: mysecretpassword
          POSTGRES_DB: mydb  # Create a database named 'mydb'
        ports: 
          - 5432:5432 
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        env:
          DATABASE_URL: postgresql://postgres:mysecretpassword@localhost:5432/mydb
        run: |
          pytest

  build:
    # ... (remains the same)

# deploy (remains commented out for now)
